### PR TITLE
refactor: refactor mem module with PODs (Plain Old Data)

### PR DESCRIPTION
**Pull request by shurizzle**
Move to type-safe and type-based memory read and write.

### CODE REVIEW

**Comment by DontPanicO** [comment]
Hi @shurizzle thanks for your contribution. I'd checked out the pr locally and played a bit with it. I wrote some very basic benchmark test (using `std::time`) and run them against the current implementation and your pr. I noticed a 25% to 30% performance decrease in writes (`mem::write` from `mem::memw`) and a 20% to 100% in reads, depending on which `mem::memr**` was tested (__N.B.__ for 16 and 32 bits reads, the performance decrease attests around 20% to 25%, with 100% noticed only with u8). 

Note that benchmarks not only tested  pure function execution, but they also included tests keeping track of u32/u16 to and from bytes (or u32 to and from U32) casting. I'll leave some example below.

As I said, I used basics and not reliable benchmark tests/environment, so I'll have to repeat tests with better tooling, thus we can have a clear picture before going any further here.

- benhmark writes:
```rust
// current
let mut memory = [0u8; 65535];
let data = u32::from_le_bytes(*b"hell");
let now = std::time::Instant::now();
mem::memw(&data.to_le_bytes(), &mut memory, 0).unwrap();
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```
vs
```rust
use crate::mem::U32;
let mut memory = [0u8; 65535];
let data = u32::from_le_bytes(*b"hell");
let now = std::time::Instant::now();
mem::write::<U32>(&U32::new(data), &mut memory, 0).unwrap();
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```
and
```rust
// current
let mut memory = [0u8; 65535];
let data = b"hell";
let now = std::time::Instant::now();
mem::memw(data, &mut memory, 0).unwrap();
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```
vs
```rust
use crate::mem::U32;
let mut memory = [0u8; 65535];
let data = U32::new(u32::from_le_bytes(*b"hell"));
let now = std::time::Instant::now();
mem::write::<U32>(&data, &mut memory, 0).unwrap();
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```

- benchmark reads:
```rust
// current
let mut memory = [0u8; 65535];
let data = b"hello_world";
mem::memw(data, &mut memory, 0).unwrap();
let now = std::time::Instant::now();
let _ = mem::memr32(&memory, 0).unwrap();
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```
vs
```rust
use crate::mem::U32;
let mut memory = [0u8; 65535];
let data = U32::new(u32::from_le_bytes(*b"hell"));
mem::write(&data, &mut memory, 0).unwrap();
let now = std::time::Instant::now();
let _ = mem::read::<U32>(&memory, 0).unwrap();
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```
and
```rust
// current
let mut memory = [0u8; 65535];
let data = b"hello_world";
mem::memw(data, &mut memory, 0).unwrap();
let now = std::time::Instant::now();
let _ = u32::from_le_bytes(mem::memr32(&memory, 0).unwrap());
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```
vs
```rust
use crate::mem::U32;
let mut memory = [0u8; 65535];
let data = U32::new(u32::from_le_bytes(*b"hell"));
mem::write(&data, &mut memory, 0).unwrap();
let now = std::time::Instant::now();
let _ = mem::read::<U32>(&memory, 0).unwrap().as_u32();
let elapsed = now.elapsed();
println!("{:?}", elapsed);
```

### Benchmark environments
I used 3 different machines to run benchmarks:
1. Ryzen 5800U, 16GB RAM, linux 6.5.11 fedora 39.
2. Ryzen 3800X, 16GB RAM, linux 6.5.11 fedora 39.
3. Intel Xeon Gold 5317, 64GB RAM, linux 6.1.55 debian 12.

**Comment by shurizzle** [comment]
Are you compiling your code in release mode?

By the way [my benchmarks](https://github.com/shurizzle/risky-membench) are different:

image

**Comment by shurizzle** [comment]
Thanks to you I optimized my implementation even more

image

**Comment by DontPanicO** [comment]
You've done a tremendous job @shurizzle. First, you were right, I was getting misleading results running in debug mode.
I tested it again (I used both bare `std::time` based tests and your bench suite) and it now matches performance.
Thank you, your help is very much appreciated 🚀

**Pull request merged**
